### ISSUE TITLE
Insufficient plural matching

### ISSUE THREAD

**Issue by stefangeyer** [tailoredmedia/gradle-localize-plugin#1]
While using localization in one of our projects, I stumbled across an issue, where plurals are parsed in an insufficient / invalid manner. 

https://github.com/tailoredmedia/gradle-localize-plugin/blob/e9d9660e005b81341943231a6825e0f3cc3d75c8/src/main/kotlin/com/tailoredapps/gradle/localize/android/ParsedSheetToAndroidTransformer.kt#L74

We currently only interpret a line as plural string, when `one|` is contained. This does not work for the following example:

```
zero|No items available
other|Available items: %d
```

To solve this issue we should either generalize the condition by matching only the `|` character (which is exhaustive, but maybe not optimal, since this could also result in false positives), or extend the list of possible matches to at least match the entries listed at the android [dev docs](https://developer.android.com/guide/topics/resources/string-resource#Plurals).

I also noticed that the same matcher is used with the [fastlane plugin](https://github.com/tailoredmedia/fastlane-plugin-localize/blob/12d15603bcc42f87ff7e1fd74bb662591b9530f5/lib/fastlane/plugin/google_sheet_localize/actions/google_sheet_localize_action.rb#L414), so the issue might also require fixing on the other platform.

**Comment by FlowMo7** [comment]
The fix has just been release as [v0.2.0](https://github.com/tailoredmedia/gradle-localize-plugin/releases/tag/v0.2.0)
