### ISSUE TITLE
Make the plugin resilient against typo fixes in the spreadsheet header (`Identifer Web`)

### ISSUE THREAD

**Issue by FlowMo7** [tailoredmedia/gradle-localize-plugin#14]
Historically, the header column had a typo in it, which the fastlane plugin seems to have hardcoded, too: `Identifer Web`.

To not break already existing sheets, this typo has been ignored and build against it.
However, the plugin should be resilient against newer sheets where this typo has been fixed.

**Comment by mariohahn** [comment]
fixed typo
