### ISSUE TITLE
Make localization config aware of buildtypes/flavors

### ISSUE THREAD

**Issue by AlexGrafl** [tailoredmedia/gradle-localize-plugin#3]
Let the configuration be extendible by the buildtypes and flavors to provide different sheetIds, tabs, languages etc. per configuration. Result should be a new gradle task per overridden type/flavor (i.e `localizeFlavor1` / `localizeFlavor2`)
Example usage:
```
localizeConfig {
    serviceAccountCredentialsFile = "./google_drive_credentials.json"
    sheetId = "<defaultSheetIdHere>"   //default/fallback
    languageTitles = ["de", "en"]

    productFlavors {
        flavor1 {
            sheetId = "<flavor1SheetIdHere>"
            localizationPath = "./src/main/res"
        }

        flavor2 {
            sheetId = "<flavor2SheetIdHere>"
            localizationPath = "./src/flavor2/res"
        }
}

**Comment by FlowMo7** [comment]
Added a first draft for an implementation for this in #4.
Adding this into the `android.buildFlavors` extension does not seem to be that easy, therefore the approach as proposed in the issue has been implemented.
The productFlavor config definitions overwrite the _base_ configuration, so all fields not defined explicitely for a flavor will fallback to the _base / default_ configuration.


I'm not sure about a build style dependent configuration, as then the library would need to implement some kind of _smarter_ merging strategy when a specific config is defined for a build type as well as a product flavor.

Currently, the specific configs are _bound_ to flavors, so if a config is defined for which no flavor is defined, then the task will fail.
As, however, the implementation does not need a link to an actual flavor, we could think about not connecting this to productFlavors at all, but just as multiple different configurations that are possible to enable. In that way we would not have any troubles for combinations of productFlavors / buildTypes, and the management of the download / processing / saving the strings.xml files into different source-sets needs to be defined by the library user in any case. What do you think about that, @AlexGrafl?

**Comment by AlexGrafl** [comment]
Yes, your suggestion would make the most sense. The configs don't actually be connected to flavors, it was just in my case where the problem came up with flavors.
